# Generated by Django 4.2.2 on 2023-07-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_bookauthor_options_remove_favoritebook_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, upload_to="covers/", verbose_name="Book Cover"
            ),
        ),
    ]
